name: Deploy docs

on:
  workflow_run:
    workflows: ['Publish Package']

jobs:
  deploy-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.workflow_run.head_commit.sha }} # checkout workflow head commit

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Build docs
        run: npm run build-docs
