name: PREVIEW_PUBLISH

on:
  workflow_run:
    workflows: ["MAIN_PULL_REQUEST"]
    types:
      - completed

jobs:
  preview-success:
    runs-on: ubuntu-latest
    if: >
      github.event.workflow_run.event == 'pull_request' &&
      github.event.workflow_run.conclusion == 'success'
    steps:
      - name: download _site artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: ${{ github.event.workflow_run.workflow_id }}
          run_id: ${{ github.event.workflow_run.id }}
          name: _site

      - shell: bash
        run: |
          if [ -f "_site.zip" ];then
            unzip _site.zip
          else
            echo "文件不存在" && exit 1
          fi

      - run: ls

      - name: save PR id
        id: pr
        run: echo "::set-output name=id::$(<_site/pr-id.txt)"
