name: testWorkflow2

on: pull_request

jobs:
  create-artifact:
    runs-on: ubuntu-latest

    steps:
      - name: Create artifact
        run: |
          echo "; echo 'attacker controlled code'; #" > artifact.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: artifact
          path: ./artifact.txt
